/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AnalyticsEventSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'eventType', 'sessionId', 'customerId', 'data', 'ipAddress', 'userAgent', 'referrer', 'createdAt'] as const
  $columns = AnalyticsEventSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare eventType: string
  @column()
  declare sessionId: string
  @column()
  declare customerId: string | null
  @column()
  declare data: any | null
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare referrer: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class ApiKeySalesChannelSchema extends BaseModel {
  static $columns = ['id', 'apiKeyId', 'salesChannelId', 'createdAt'] as const
  $columns = ApiKeySalesChannelSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare apiKeyId: string
  @column()
  declare salesChannelId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class ApiKeySchema extends BaseModel {
  static $columns = ['id', 'storeId', 'title', 'type', 'tokenHash', 'last4', 'prefix', 'createdBy', 'revokedAt', 'lastUsedAt', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = ApiKeySchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column()
  declare tokenHash: string
  @column()
  declare last4: string
  @column()
  declare prefix: string
  @column()
  declare createdBy: number | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare metadata: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AttributeOptionSchema extends BaseModel {
  static $columns = ['id', 'attributeId', 'label', 'value', 'position', 'colorCode', 'createdAt', 'updatedAt'] as const
  $columns = AttributeOptionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare attributeId: string | null
  @column()
  declare label: string
  @column()
  declare value: string
  @column()
  declare position: number | null
  @column()
  declare colorCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AttributeSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'code', 'name', 'type', 'isRequired', 'isFilterable', 'isVisibleOnFront', 'isSearchable', 'isComparable', 'validationRules', 'position', 'createdAt', 'updatedAt'] as const
  $columns = AttributeSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare code: string
  @column()
  declare name: string
  @column()
  declare type: string
  @column()
  declare isRequired: boolean | null
  @column()
  declare isFilterable: boolean | null
  @column()
  declare isVisibleOnFront: boolean | null
  @column()
  declare isSearchable: boolean | null
  @column()
  declare isComparable: boolean | null
  @column()
  declare validationRules: any | null
  @column()
  declare position: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BannerSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'title', 'subtitle', 'imageUrl', 'mobileImageUrl', 'linkUrl', 'linkTarget', 'position', 'sortOrder', 'isActive', 'startsAt', 'endsAt', 'createdAt', 'updatedAt'] as const
  $columns = BannerSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare title: string
  @column()
  declare subtitle: string | null
  @column()
  declare imageUrl: string
  @column()
  declare mobileImageUrl: string | null
  @column()
  declare linkUrl: string | null
  @column()
  declare linkTarget: string | null
  @column()
  declare position: string | null
  @column()
  declare sortOrder: number | null
  @column()
  declare isActive: boolean | null
  @column.dateTime()
  declare startsAt: DateTime | null
  @column.dateTime()
  declare endsAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BlogCategorySchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'slug', 'description', 'sortOrder', 'createdAt', 'updatedAt'] as const
  $columns = BlogCategorySchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column()
  declare sortOrder: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BlogPostSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'blogCategoryId', 'authorId', 'title', 'slug', 'excerpt', 'content', 'featuredImageUrl', 'status', 'tags', 'metaTitle', 'metaDescription', 'isFeatured', 'viewCount', 'publishedAt', 'createdAt', 'updatedAt'] as const
  $columns = BlogPostSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string
  @column()
  declare blogCategoryId: string | null
  @column()
  declare authorId: number | null
  @column()
  declare title: string
  @column()
  declare slug: string
  @column()
  declare excerpt: string | null
  @column()
  declare content: string | null
  @column()
  declare featuredImageUrl: string | null
  @column()
  declare status: string | null
  @column()
  declare tags: any | null
  @column()
  declare metaTitle: string | null
  @column()
  declare metaDescription: string | null
  @column()
  declare isFeatured: boolean | null
  @column()
  declare viewCount: number | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CartItemSchema extends BaseModel {
  static $columns = ['id', 'cartId', 'productId', 'variantId', 'sku', 'title', 'variantTitle', 'quantity', 'unitPrice', 'totalPrice', 'discountAmount', 'taxAmount', 'weight', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = CartItemSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare cartId: string | null
  @column()
  declare productId: string | null
  @column()
  declare variantId: string | null
  @column()
  declare sku: string
  @column()
  declare title: string
  @column()
  declare variantTitle: string | null
  @column()
  declare quantity: number
  @column()
  declare unitPrice: string
  @column()
  declare totalPrice: string
  @column()
  declare discountAmount: string | null
  @column()
  declare taxAmount: string | null
  @column()
  declare weight: string | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CartSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'customerId', 'sessionId', 'email', 'currencyCode', 'subtotal', 'discountTotal', 'taxTotal', 'shippingTotal', 'grandTotal', 'totalItems', 'totalQuantity', 'couponCode', 'discountId', 'billingAddressId', 'shippingAddressId', 'shippingMethod', 'paymentMethod', 'notes', 'metadata', 'completedAt', 'expiresAt', 'createdAt', 'updatedAt'] as const
  $columns = CartSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare customerId: string | null
  @column()
  declare sessionId: string | null
  @column()
  declare email: string | null
  @column()
  declare currencyCode: string | null
  @column()
  declare subtotal: string | null
  @column()
  declare discountTotal: string | null
  @column()
  declare taxTotal: string | null
  @column()
  declare shippingTotal: string | null
  @column()
  declare grandTotal: string | null
  @column()
  declare totalItems: number | null
  @column()
  declare totalQuantity: number | null
  @column()
  declare couponCode: string | null
  @column()
  declare discountId: string | null
  @column()
  declare billingAddressId: string | null
  @column()
  declare shippingAddressId: string | null
  @column()
  declare shippingMethod: string | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare notes: string | null
  @column()
  declare metadata: any | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategorySchema extends BaseModel {
  static $columns = ['id', 'storeId', 'parentId', 'name', 'slug', 'description', 'imageUrl', 'position', 'depth', 'path', 'isActive', 'metaTitle', 'metaDescription', 'createdAt', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare parentId: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column()
  declare imageUrl: string | null
  @column()
  declare position: number | null
  @column()
  declare depth: number | null
  @column()
  declare path: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare metaTitle: string | null
  @column()
  declare metaDescription: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ClaimItemSchema extends BaseModel {
  static $columns = ['id', 'claimId', 'orderItemId', 'quantity', 'reason', 'note', 'images', 'tags', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = ClaimItemSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare claimId: string | null
  @column()
  declare orderItemId: string | null
  @column()
  declare quantity: number
  @column()
  declare reason: string
  @column()
  declare note: string | null
  @column()
  declare images: any | null
  @column()
  declare tags: any | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ClaimSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'orderId', 'type', 'status', 'refundAmount', 'note', 'internalNote', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = ClaimSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare orderId: string | null
  @column()
  declare type: string
  @column()
  declare status: string | null
  @column()
  declare refundAmount: string | null
  @column()
  declare note: string | null
  @column()
  declare internalNote: string | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CollectionProductSchema extends BaseModel {
  static $columns = ['collectionId', 'productId', 'position'] as const
  $columns = CollectionProductSchema.$columns
  @column()
  declare collectionId: string
  @column()
  declare productId: string
  @column()
  declare position: number | null
}

export class CollectionSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'slug', 'description', 'type', 'conditions', 'imageUrl', 'isActive', 'sortOrder', 'metadata', 'publishedAt', 'createdAt', 'updatedAt'] as const
  $columns = CollectionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column()
  declare type: string | null
  @column()
  declare conditions: any | null
  @column()
  declare imageUrl: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare sortOrder: number | null
  @column()
  declare metadata: any | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CurrencySchema extends BaseModel {
  static $columns = ['id', 'storeId', 'code', 'name', 'symbol', 'symbolPosition', 'decimalSeparator', 'thousandsSeparator', 'decimalPlaces', 'exchangeRate', 'isDefault', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = CurrencySchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare code: string
  @column()
  declare name: string
  @column()
  declare symbol: string
  @column()
  declare symbolPosition: string | null
  @column()
  declare decimalSeparator: string | null
  @column()
  declare thousandsSeparator: string | null
  @column()
  declare decimalPlaces: number | null
  @column()
  declare exchangeRate: string | null
  @column()
  declare isDefault: boolean | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerAddressSchema extends BaseModel {
  static $columns = ['id', 'customerId', 'type', 'isDefault', 'firstName', 'lastName', 'company', 'addressLine1', 'addressLine2', 'city', 'state', 'postalCode', 'countryCode', 'phone', 'createdAt', 'updatedAt'] as const
  $columns = CustomerAddressSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare customerId: string | null
  @column()
  declare type: string | null
  @column()
  declare isDefault: boolean | null
  @column()
  declare firstName: string
  @column()
  declare lastName: string
  @column()
  declare company: string | null
  @column()
  declare addressLine1: string
  @column()
  declare addressLine2: string | null
  @column()
  declare city: string
  @column()
  declare state: string | null
  @column()
  declare postalCode: string
  @column()
  declare countryCode: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerGroupSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'slug', 'description', 'conditions', 'isActive', 'createdAt', 'updatedAt', 'discountPercentage', 'isDefault'] as const
  $columns = CustomerGroupSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column()
  declare conditions: any | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare discountPercentage: string | null
  @column()
  declare isDefault: boolean | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'email', 'passwordHash', 'firstName', 'lastName', 'phone', 'avatarUrl', 'status', 'acceptsMarketing', 'totalOrders', 'totalSpent', 'lastOrderAt', 'tags', 'notes', 'metadata', 'emailVerifiedAt', 'createdAt', 'updatedAt', 'deletedAt', 'groupId', 'oauthProvider', 'oauthProviderId', 'oauthAvatarUrl'] as const
  $columns = CustomerSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare email: string
  @column()
  declare passwordHash: string | null
  @column()
  declare firstName: string
  @column()
  declare lastName: string
  @column()
  declare phone: string | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare status: string | null
  @column()
  declare acceptsMarketing: boolean | null
  @column()
  declare totalOrders: number | null
  @column()
  declare totalSpent: string | null
  @column.dateTime()
  declare lastOrderAt: DateTime | null
  @column()
  declare tags: any | null
  @column()
  declare notes: string | null
  @column()
  declare metadata: any | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare groupId: string | null
  @column()
  declare oauthProvider: string | null
  @column()
  declare oauthProviderId: string | null
  @column()
  declare oauthAvatarUrl: string | null
}

export class DailyAnalyticSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'date', 'totalOrders', 'totalRevenue', 'totalCustomers', 'newCustomers', 'averageOrderValue', 'totalItemsSold', 'totalRefunds', 'topProducts', 'conversionRate', 'createdAt', 'updatedAt'] as const
  $columns = DailyAnalyticSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare storeId: string | null
  @column.date()
  declare date: DateTime
  @column()
  declare totalOrders: number | null
  @column()
  declare totalRevenue: string | null
  @column()
  declare totalCustomers: number | null
  @column()
  declare newCustomers: number | null
  @column()
  declare averageOrderValue: string | null
  @column()
  declare totalItemsSold: number | null
  @column()
  declare totalRefunds: string | null
  @column()
  declare topProducts: any | null
  @column()
  declare conversionRate: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DiscountSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'code', 'type', 'value', 'appliesTo', 'productIds', 'categoryIds', 'customerIds', 'minimumOrderAmount', 'maximumOrderAmount', 'minimumQuantity', 'maximumDiscountAmount', 'usageLimit', 'usageLimitPerCustomer', 'usageCount', 'isActive', 'isPublic', 'firstOrderOnly', 'startsAt', 'endsAt', 'buyQuantity', 'getQuantity', 'getDiscountPercentage', 'isAutomatic', 'priority', 'isCombinable', 'createdAt', 'updatedAt', 'campaignName', 'budgetType', 'budgetLimit', 'budgetUsed', 'customerGroupIds', 'regionIds'] as const
  $columns = DiscountSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare code: string
  @column()
  declare type: string
  @column()
  declare value: string
  @column()
  declare appliesTo: string | null
  @column()
  declare productIds: any | null
  @column()
  declare categoryIds: any | null
  @column()
  declare customerIds: any | null
  @column()
  declare minimumOrderAmount: string | null
  @column()
  declare maximumOrderAmount: string | null
  @column()
  declare minimumQuantity: number | null
  @column()
  declare maximumDiscountAmount: string | null
  @column()
  declare usageLimit: number | null
  @column()
  declare usageLimitPerCustomer: number | null
  @column()
  declare usageCount: number | null
  @column()
  declare isActive: boolean | null
  @column()
  declare isPublic: boolean | null
  @column()
  declare firstOrderOnly: boolean | null
  @column.dateTime()
  declare startsAt: DateTime | null
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare buyQuantity: number | null
  @column()
  declare getQuantity: number | null
  @column()
  declare getDiscountPercentage: number | null
  @column()
  declare isAutomatic: boolean | null
  @column()
  declare priority: number | null
  @column()
  declare isCombinable: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare campaignName: string | null
  @column()
  declare budgetType: string | null
  @column()
  declare budgetLimit: string | null
  @column()
  declare budgetUsed: string | null
  @column()
  declare customerGroupIds: any | null
  @column()
  declare regionIds: any | null
}

export class DraftOrderSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'displayId', 'status', 'customerId', 'email', 'regionId', 'currencyCode', 'items', 'shippingAddress', 'billingAddress', 'shippingMethod', 'shippingTotal', 'discountTotal', 'taxTotal', 'subtotal', 'grandTotal', 'note', 'orderId', 'createdBy', 'metadata', 'completedAt', 'createdAt', 'updatedAt'] as const
  $columns = DraftOrderSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare displayId: string
  @column()
  declare status: string | null
  @column()
  declare customerId: string | null
  @column()
  declare email: string | null
  @column()
  declare regionId: string | null
  @column()
  declare currencyCode: string
  @column()
  declare items: any | null
  @column()
  declare shippingAddress: any | null
  @column()
  declare billingAddress: any | null
  @column()
  declare shippingMethod: string | null
  @column()
  declare shippingTotal: string | null
  @column()
  declare discountTotal: string | null
  @column()
  declare taxTotal: string | null
  @column()
  declare subtotal: string | null
  @column()
  declare grandTotal: string | null
  @column()
  declare note: string | null
  @column()
  declare orderId: string | null
  @column()
  declare createdBy: number | null
  @column()
  declare metadata: any | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmailCampaignSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'subject', 'body', 'status', 'recipientCount', 'openRate', 'clickRate', 'scheduledAt', 'sentAt', 'createdAt', 'updatedAt'] as const
  $columns = EmailCampaignSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare subject: string
  @column()
  declare body: string
  @column()
  declare status: string
  @column()
  declare recipientCount: number
  @column()
  declare openRate: string | null
  @column()
  declare clickRate: string | null
  @column.dateTime()
  declare scheduledAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ExchangeSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'orderId', 'returnId', 'status', 'differenceAmount', 'paymentStatus', 'note', 'newItems', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = ExchangeSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare orderId: string | null
  @column()
  declare returnId: string | null
  @column()
  declare status: string | null
  @column()
  declare differenceAmount: string | null
  @column()
  declare paymentStatus: string | null
  @column()
  declare note: string | null
  @column()
  declare newItems: any | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FulfillmentItemSchema extends BaseModel {
  static $columns = ['id', 'fulfillmentId', 'orderItemId', 'quantity'] as const
  $columns = FulfillmentItemSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare fulfillmentId: string | null
  @column()
  declare orderItemId: string | null
  @column()
  declare quantity: number
}

export class FulfillmentSchema extends BaseModel {
  static $columns = ['id', 'orderId', 'trackingNumber', 'trackingUrl', 'carrier', 'carrierName', 'status', 'shippedAt', 'deliveredAt', 'notes', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = FulfillmentSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string | null
  @column()
  declare trackingNumber: string | null
  @column()
  declare trackingUrl: string | null
  @column()
  declare carrier: string | null
  @column()
  declare carrierName: string | null
  @column()
  declare status: string | null
  @column.dateTime()
  declare shippedAt: DateTime | null
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare notes: string | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class GiftCardTransactionSchema extends BaseModel {
  static $columns = ['id', 'giftCardId', 'orderId', 'amount', 'type', 'note', 'createdAt'] as const
  $columns = GiftCardTransactionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare giftCardId: string
  @column()
  declare orderId: string | null
  @column()
  declare amount: string
  @column()
  declare type: string
  @column()
  declare note: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class GiftCardSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'code', 'value', 'balance', 'currencyCode', 'isDisabled', 'regionId', 'orderId', 'endsAt', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = GiftCardSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string
  @column()
  declare code: string
  @column()
  declare value: string
  @column()
  declare balance: string
  @column()
  declare currencyCode: string
  @column()
  declare isDisabled: boolean
  @column()
  declare regionId: string | null
  @column()
  declare orderId: string | null
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare metadata: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InventoryItemSchema extends BaseModel {
  static $columns = ['id', 'variantId', 'locationId', 'quantity', 'reservedQuantity', 'availableQuantity', 'reorderPoint', 'reorderQuantity', 'createdAt', 'updatedAt'] as const
  $columns = InventoryItemSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare variantId: string | null
  @column()
  declare locationId: string | null
  @column()
  declare quantity: number | null
  @column()
  declare reservedQuantity: number | null
  @column()
  declare availableQuantity: number | null
  @column()
  declare reorderPoint: number | null
  @column()
  declare reorderQuantity: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InventoryLocationSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'code', 'address', 'isActive', 'isFulfillmentCenter', 'priority', 'createdAt', 'updatedAt'] as const
  $columns = InventoryLocationSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare code: string
  @column()
  declare address: any | null
  @column()
  declare isActive: boolean | null
  @column()
  declare isFulfillmentCenter: boolean | null
  @column()
  declare priority: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InventoryMovementSchema extends BaseModel {
  static $columns = ['id', 'inventoryItemId', 'type', 'quantity', 'referenceType', 'referenceId', 'reason', 'userId', 'createdAt'] as const
  $columns = InventoryMovementSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inventoryItemId: string | null
  @column()
  declare type: string
  @column()
  declare quantity: number
  @column()
  declare referenceType: string | null
  @column()
  declare referenceId: string | null
  @column()
  declare reason: string | null
  @column()
  declare userId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class InventoryReservationSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'variantId', 'locationId', 'lineItemId', 'type', 'quantity', 'description', 'createdBy', 'expiresAt', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = InventoryReservationSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string
  @column()
  declare variantId: string
  @column()
  declare locationId: string | null
  @column()
  declare lineItemId: string | null
  @column()
  declare type: string
  @column()
  declare quantity: number
  @column()
  declare description: string | null
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare metadata: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LocaleSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'code', 'name', 'nativeName', 'isDefault', 'isActive', 'direction', 'createdAt', 'updatedAt'] as const
  $columns = LocaleSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare code: string
  @column()
  declare name: string
  @column()
  declare nativeName: string | null
  @column()
  declare isDefault: boolean | null
  @column()
  declare isActive: boolean | null
  @column()
  declare direction: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MenuItemSchema extends BaseModel {
  static $columns = ['id', 'menuId', 'parentId', 'title', 'url', 'type', 'referenceId', 'target', 'icon', 'sortOrder', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = MenuItemSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare menuId: string | null
  @column()
  declare parentId: string | null
  @column()
  declare title: string
  @column()
  declare url: string | null
  @column()
  declare type: string | null
  @column()
  declare referenceId: string | null
  @column()
  declare target: string | null
  @column()
  declare icon: string | null
  @column()
  declare sortOrder: number | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MenuSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'slug', 'createdAt', 'updatedAt', 'location', 'isActive'] as const
  $columns = MenuSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare location: string | null
  @column()
  declare isActive: boolean | null
}

export class NotificationTemplateSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'event', 'channel', 'subject', 'body', 'isActive', 'locale', 'createdAt', 'updatedAt', 'name', 'slug', 'variables'] as const
  $columns = NotificationTemplateSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare event: string
  @column()
  declare channel: string
  @column()
  declare subject: string
  @column()
  declare body: string
  @column()
  declare isActive: boolean | null
  @column()
  declare locale: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare name: string | null
  @column()
  declare slug: string | null
  @column()
  declare variables: any | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'type', 'notifiableType', 'notifiableId', 'channel', 'subject', 'body', 'data', 'readAt', 'sentAt', 'failedAt', 'error', 'createdAt', 'userId', 'title', 'message', 'isRead'] as const
  $columns = NotificationSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare type: string
  @column()
  declare notifiableType: string
  @column()
  declare notifiableId: string
  @column()
  declare channel: string
  @column()
  declare subject: string
  @column()
  declare body: string
  @column()
  declare data: any | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column.dateTime()
  declare failedAt: DateTime | null
  @column()
  declare error: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare userId: number | null
  @column()
  declare title: string | null
  @column()
  declare message: string | null
  @column()
  declare isRead: boolean | null
}

export class OrderEditSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'orderId', 'createdBy', 'status', 'internalNote', 'differenceAmount', 'changes', 'requestedAt', 'confirmedAt', 'declinedAt', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = OrderEditSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare orderId: string | null
  @column()
  declare createdBy: number | null
  @column()
  declare status: string | null
  @column()
  declare internalNote: string | null
  @column()
  declare differenceAmount: string | null
  @column()
  declare changes: any | null
  @column.dateTime()
  declare requestedAt: DateTime | null
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column.dateTime()
  declare declinedAt: DateTime | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['id', 'orderId', 'productId', 'variantId', 'sku', 'title', 'variantTitle', 'quantity', 'unitPrice', 'totalPrice', 'discountAmount', 'taxAmount', 'taxRate', 'weight', 'fulfilledQuantity', 'returnedQuantity', 'thumbnailUrl', 'properties', 'createdAt', 'updatedAt'] as const
  $columns = OrderItemSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string | null
  @column()
  declare productId: string | null
  @column()
  declare variantId: string | null
  @column()
  declare sku: string
  @column()
  declare title: string
  @column()
  declare variantTitle: string | null
  @column()
  declare quantity: number
  @column()
  declare unitPrice: string
  @column()
  declare totalPrice: string
  @column()
  declare discountAmount: string | null
  @column()
  declare taxAmount: string | null
  @column()
  declare taxRate: string | null
  @column()
  declare weight: string | null
  @column()
  declare fulfilledQuantity: number | null
  @column()
  declare returnedQuantity: number | null
  @column()
  declare thumbnailUrl: string | null
  @column()
  declare properties: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderStatusHistorySchema extends BaseModel {
  static $columns = ['id', 'orderId', 'status', 'previousStatus', 'type', 'title', 'description', 'userId', 'isCustomerNotified', 'metadata', 'createdAt'] as const
  $columns = OrderStatusHistorySchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string | null
  @column()
  declare status: string
  @column()
  declare previousStatus: string | null
  @column()
  declare type: string | null
  @column()
  declare title: string
  @column()
  declare description: string | null
  @column()
  declare userId: number | null
  @column()
  declare isCustomerNotified: boolean | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class OrderTransactionSchema extends BaseModel {
  static $columns = ['id', 'orderId', 'type', 'status', 'amount', 'currencyCode', 'paymentMethod', 'gatewayTransactionId', 'gatewayResponse', 'errorMessage', 'processedAt', 'createdAt', 'updatedAt'] as const
  $columns = OrderTransactionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string | null
  @column()
  declare type: string
  @column()
  declare status: string | null
  @column()
  declare amount: string
  @column()
  declare currencyCode: string
  @column()
  declare paymentMethod: string
  @column()
  declare gatewayTransactionId: string | null
  @column()
  declare gatewayResponse: any | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare processedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'orderNumber', 'customerId', 'email', 'phone', 'status', 'paymentStatus', 'fulfillmentStatus', 'currencyCode', 'subtotal', 'discountTotal', 'taxTotal', 'shippingTotal', 'grandTotal', 'totalPaid', 'totalRefunded', 'couponCode', 'discountId', 'billingAddress', 'shippingAddress', 'shippingMethod', 'shippingMethodTitle', 'paymentMethod', 'paymentMethodTitle', 'notes', 'internalNotes', 'metadata', 'ipAddress', 'userAgent', 'cancelledAt', 'cancelReason', 'placedAt', 'createdAt', 'updatedAt', 'deletedAt', 'regionId', 'salesChannelId'] as const
  $columns = OrderSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare orderNumber: string
  @column()
  declare customerId: string | null
  @column()
  declare email: string
  @column()
  declare phone: string | null
  @column()
  declare status: string | null
  @column()
  declare paymentStatus: string | null
  @column()
  declare fulfillmentStatus: string | null
  @column()
  declare currencyCode: string
  @column()
  declare subtotal: string
  @column()
  declare discountTotal: string | null
  @column()
  declare taxTotal: string | null
  @column()
  declare shippingTotal: string | null
  @column()
  declare grandTotal: string
  @column()
  declare totalPaid: string | null
  @column()
  declare totalRefunded: string | null
  @column()
  declare couponCode: string | null
  @column()
  declare discountId: string | null
  @column()
  declare billingAddress: any
  @column()
  declare shippingAddress: any
  @column()
  declare shippingMethod: string | null
  @column()
  declare shippingMethodTitle: string | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare paymentMethodTitle: string | null
  @column()
  declare notes: string | null
  @column()
  declare internalNotes: string | null
  @column()
  declare metadata: any | null
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelReason: string | null
  @column.dateTime()
  declare placedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare regionId: string | null
  @column()
  declare salesChannelId: string | null
}

export class PageSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'title', 'slug', 'content', 'template', 'status', 'isSystem', 'metaTitle', 'metaDescription', 'publishedAt', 'createdAt', 'updatedAt'] as const
  $columns = PageSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare title: string
  @column()
  declare slug: string
  @column()
  declare content: any | null
  @column()
  declare template: string | null
  @column()
  declare status: string | null
  @column()
  declare isSystem: boolean | null
  @column()
  declare metaTitle: string | null
  @column()
  declare metaDescription: string | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PermissionSchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'description', 'group', 'createdAt', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column()
  declare group: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PriceListPriceSchema extends BaseModel {
  static $columns = ['id', 'priceListId', 'variantId', 'amount', 'currencyCode', 'minQuantity', 'maxQuantity', 'createdAt', 'updatedAt'] as const
  $columns = PriceListPriceSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare priceListId: string | null
  @column()
  declare variantId: string | null
  @column()
  declare amount: string
  @column()
  declare currencyCode: string
  @column()
  declare minQuantity: number | null
  @column()
  declare maxQuantity: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PriceListRuleSchema extends BaseModel {
  static $columns = ['id', 'priceListId', 'attribute', 'operator', 'value', 'createdAt', 'updatedAt'] as const
  $columns = PriceListRuleSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare priceListId: string | null
  @column()
  declare attribute: string
  @column()
  declare operator: string
  @column()
  declare value: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PriceListSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'description', 'type', 'status', 'startsAt', 'endsAt', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = PriceListSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare type: string
  @column()
  declare status: string
  @column.dateTime()
  declare startsAt: DateTime | null
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductAttributeValueSchema extends BaseModel {
  static $columns = ['id', 'productId', 'attributeId', 'textValue', 'numberValue', 'booleanValue', 'dateValue', 'optionId', 'jsonValue', 'locale', 'createdAt', 'updatedAt'] as const
  $columns = ProductAttributeValueSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string | null
  @column()
  declare attributeId: string | null
  @column()
  declare textValue: string | null
  @column()
  declare numberValue: string | null
  @column()
  declare booleanValue: boolean | null
  @column.date()
  declare dateValue: DateTime | null
  @column()
  declare optionId: string | null
  @column()
  declare jsonValue: any | null
  @column()
  declare locale: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductCategorySchema extends BaseModel {
  static $columns = ['productId', 'categoryId', 'position'] as const
  $columns = ProductCategorySchema.$columns
  @column()
  declare productId: string
  @column()
  declare categoryId: string
  @column()
  declare position: number | null
}

export class ProductImageSchema extends BaseModel {
  static $columns = ['id', 'productId', 'url', 'altText', 'position', 'width', 'height', 'fileSize', 'mimeType', 'createdAt', 'updatedAt'] as const
  $columns = ProductImageSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string | null
  @column()
  declare url: string
  @column()
  declare altText: string | null
  @column()
  declare position: number | null
  @column()
  declare width: number | null
  @column()
  declare height: number | null
  @column()
  declare fileSize: number | null
  @column()
  declare mimeType: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductOptionSchema extends BaseModel {
  static $columns = ['id', 'productId', 'name', 'position', 'values', 'createdAt', 'updatedAt'] as const
  $columns = ProductOptionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string | null
  @column()
  declare name: string
  @column()
  declare position: number | null
  @column()
  declare values: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductSalesChannelSchema extends BaseModel {
  static $columns = ['id', 'productId', 'salesChannelId', 'createdAt'] as const
  $columns = ProductSalesChannelSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string | null
  @column()
  declare salesChannelId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class ProductTagSchema extends BaseModel {
  static $columns = ['productId', 'tagId'] as const
  $columns = ProductTagSchema.$columns
  @column()
  declare productId: string
  @column()
  declare tagId: string
}

export class ProductVariantSchema extends BaseModel {
  static $columns = ['id', 'productId', 'title', 'sku', 'barcode', 'price', 'compareAtPrice', 'costPrice', 'weight', 'option1', 'option2', 'option3', 'imageId', 'position', 'isActive', 'inventoryQuantity', 'stockQuantity', 'trackInventory', 'allowBackorder', 'requiresShipping', 'createdAt', 'updatedAt', 'deletedAt'] as const
  $columns = ProductVariantSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string | null
  @column()
  declare title: string
  @column()
  declare sku: string
  @column()
  declare barcode: string | null
  @column()
  declare price: string
  @column()
  declare compareAtPrice: string | null
  @column()
  declare costPrice: string | null
  @column()
  declare weight: string | null
  @column()
  declare option1: string | null
  @column()
  declare option2: string | null
  @column()
  declare option3: string | null
  @column()
  declare imageId: string | null
  @column()
  declare position: number | null
  @column()
  declare isActive: boolean | null
  @column()
  declare inventoryQuantity: number | null
  @column()
  declare stockQuantity: number | null
  @column()
  declare trackInventory: boolean | null
  @column()
  declare allowBackorder: boolean | null
  @column()
  declare requiresShipping: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'title', 'slug', 'description', 'shortDescription', 'status', 'type', 'vendor', 'sku', 'barcode', 'price', 'compareAtPrice', 'costPrice', 'isTaxable', 'taxClassId', 'weight', 'weightUnit', 'requiresShipping', 'trackInventory', 'stockQuantity', 'hasVariants', 'isFeatured', 'sortOrder', 'metaTitle', 'metaDescription', 'metaKeywords', 'customFields', 'publishedAt', 'createdAt', 'updatedAt', 'deletedAt', 'shippingProfileId'] as const
  $columns = ProductSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare title: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column()
  declare shortDescription: string | null
  @column()
  declare status: string | null
  @column()
  declare type: string | null
  @column()
  declare vendor: string | null
  @column()
  declare sku: string | null
  @column()
  declare barcode: string | null
  @column()
  declare price: string | null
  @column()
  declare compareAtPrice: string | null
  @column()
  declare costPrice: string | null
  @column()
  declare isTaxable: boolean | null
  @column()
  declare taxClassId: string | null
  @column()
  declare weight: string | null
  @column()
  declare weightUnit: string | null
  @column()
  declare requiresShipping: boolean | null
  @column()
  declare trackInventory: boolean | null
  @column()
  declare stockQuantity: number | null
  @column()
  declare hasVariants: boolean | null
  @column()
  declare isFeatured: boolean | null
  @column()
  declare sortOrder: number | null
  @column()
  declare metaTitle: string | null
  @column()
  declare metaDescription: string | null
  @column()
  declare metaKeywords: string | null
  @column()
  declare customFields: any | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare shippingProfileId: string | null
}

export class RefundItemSchema extends BaseModel {
  static $columns = ['id', 'refundId', 'orderItemId', 'quantity', 'amount', 'restock'] as const
  $columns = RefundItemSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare refundId: string | null
  @column()
  declare orderItemId: string | null
  @column()
  declare quantity: number
  @column()
  declare amount: string
  @column()
  declare restock: boolean | null
}

export class RefundSchema extends BaseModel {
  static $columns = ['id', 'orderId', 'amount', 'reason', 'notes', 'status', 'refundedBy', 'createdAt', 'updatedAt'] as const
  $columns = RefundSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string | null
  @column()
  declare amount: string
  @column()
  declare reason: string | null
  @column()
  declare notes: string | null
  @column()
  declare status: string | null
  @column()
  declare refundedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RegionCountrySchema extends BaseModel {
  static $columns = ['id', 'regionId', 'countryCode', 'countryName', 'createdAt', 'updatedAt'] as const
  $columns = RegionCountrySchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare regionId: string | null
  @column()
  declare countryCode: string
  @column()
  declare countryName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RegionSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'currencyCode', 'taxRate', 'taxCode', 'includesTax', 'paymentProviders', 'fulfillmentProviders', 'isActive', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = RegionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare currencyCode: string
  @column()
  declare taxRate: string | null
  @column()
  declare taxCode: string | null
  @column()
  declare includesTax: boolean | null
  @column()
  declare paymentProviders: any | null
  @column()
  declare fulfillmentProviders: any | null
  @column()
  declare isActive: boolean | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'hash', 'createdAt', 'updatedAt', 'expiresAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare hash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
}

export class ReturnItemSchema extends BaseModel {
  static $columns = ['id', 'returnId', 'orderItemId', 'returnReasonId', 'quantity', 'receivedQuantity', 'note', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = ReturnItemSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare returnId: string | null
  @column()
  declare orderItemId: string | null
  @column()
  declare returnReasonId: string | null
  @column()
  declare quantity: number
  @column()
  declare receivedQuantity: number | null
  @column()
  declare note: string | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReturnReasonSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'parentId', 'value', 'label', 'description', 'sortOrder', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = ReturnReasonSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare parentId: string | null
  @column()
  declare value: string
  @column()
  declare label: string
  @column()
  declare description: string | null
  @column()
  declare sortOrder: number | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReturnSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'orderId', 'status', 'refundAmount', 'shippingMethod', 'trackingNumber', 'note', 'internalNote', 'receivedBy', 'receivedAt', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = ReturnSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare orderId: string | null
  @column()
  declare status: string | null
  @column()
  declare refundAmount: string | null
  @column()
  declare shippingMethod: string | null
  @column()
  declare trackingNumber: string | null
  @column()
  declare note: string | null
  @column()
  declare internalNote: string | null
  @column()
  declare receivedBy: string | null
  @column.dateTime()
  declare receivedAt: DateTime | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReviewSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'productId', 'customerId', 'orderId', 'rating', 'title', 'body', 'status', 'isVerifiedPurchase', 'helpfulCount', 'adminResponse', 'adminRespondedAt', 'createdAt', 'updatedAt'] as const
  $columns = ReviewSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare productId: string | null
  @column()
  declare customerId: string | null
  @column()
  declare orderId: string | null
  @column()
  declare rating: number
  @column()
  declare title: string | null
  @column()
  declare body: string
  @column()
  declare status: string | null
  @column()
  declare isVerifiedPurchase: boolean | null
  @column()
  declare helpfulCount: number | null
  @column()
  declare adminResponse: string | null
  @column.dateTime()
  declare adminRespondedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['roleId', 'permissionId'] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare roleId: string
  @column()
  declare permissionId: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'description', 'isSystem', 'createdAt', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column()
  declare isSystem: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SalesChannelSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'description', 'isActive', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = SalesChannelSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SearchLogSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'query', 'resultsCount', 'customerId', 'createdAt'] as const
  $columns = SearchLogSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare query: string
  @column()
  declare resultsCount: number | null
  @column()
  declare customerId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class SearchSynonymSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'terms', 'createdAt', 'updatedAt'] as const
  $columns = SearchSynonymSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare terms: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SettingSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'group', 'key', 'value', 'isPublic', 'createdAt', 'updatedAt', 'type'] as const
  $columns = SettingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare storeId: string | null
  @column()
  declare group: string
  @column()
  declare key: string
  @column()
  declare value: any | null
  @column()
  declare isPublic: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare type: string | null
}

export class ShippingProfileSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'type', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = ShippingProfileSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string
  @column()
  declare name: string
  @column()
  declare type: string
  @column()
  declare metadata: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class StoreSchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'domain', 'logoUrl', 'defaultLocale', 'defaultCurrency', 'timezone', 'isActive', 'settings', 'meta', 'createdAt', 'updatedAt'] as const
  $columns = StoreSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare domain: string | null
  @column()
  declare logoUrl: string | null
  @column()
  declare defaultLocale: string | null
  @column()
  declare defaultCurrency: string | null
  @column()
  declare timezone: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare settings: any | null
  @column()
  declare meta: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TagSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'slug', 'createdAt', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaxClassSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'description', 'isDefault', 'createdAt', 'updatedAt'] as const
  $columns = TaxClassSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare isDefault: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaxRateSchema extends BaseModel {
  static $columns = ['id', 'taxClassId', 'name', 'rate', 'countryCode', 'stateCode', 'postalCode', 'priority', 'isCompound', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = TaxRateSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare taxClassId: string | null
  @column()
  declare name: string
  @column()
  declare rate: string
  @column()
  declare countryCode: string
  @column()
  declare stateCode: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare priority: number | null
  @column()
  declare isCompound: boolean | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TranslationSchema extends BaseModel {
  static $columns = ['id', 'locale', 'translatableType', 'translatableId', 'field', 'value', 'createdAt', 'updatedAt'] as const
  $columns = TranslationSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare locale: string
  @column()
  declare translatableType: string
  @column()
  declare translatableId: string
  @column()
  declare field: string
  @column()
  declare value: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UrlRedirectSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'sourcePath', 'targetPath', 'type', 'isActive', 'createdAt', 'updatedAt', 'hitCount', 'lastHitAt'] as const
  $columns = UrlRedirectSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare sourcePath: string
  @column()
  declare targetPath: string
  @column()
  declare type: string | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare hitCount: number | null
  @column.dateTime()
  declare lastHitAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'createdAt', 'updatedAt', 'roleId', 'firstName', 'lastName', 'avatarUrl', 'isActive', 'lastLoginAt', 'twoFactorSecret', 'twoFactorEnabled'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare roleId: string | null
  @column()
  declare firstName: string | null
  @column()
  declare lastName: string | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare isActive: boolean | null
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare twoFactorSecret: string | null
  @column()
  declare twoFactorEnabled: boolean | null
}

export class WebhookLogSchema extends BaseModel {
  static $columns = ['id', 'webhookId', 'event', 'payload', 'responseStatus', 'responseBody', 'durationMs', 'error', 'createdAt'] as const
  $columns = WebhookLogSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare webhookId: string | null
  @column()
  declare event: string
  @column()
  declare payload: any
  @column()
  declare responseStatus: number | null
  @column()
  declare responseBody: string | null
  @column()
  declare durationMs: number | null
  @column()
  declare error: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class WebhookSchema extends BaseModel {
  static $columns = ['id', 'storeId', 'name', 'url', 'secret', 'events', 'isActive', 'lastTriggeredAt', 'failureCount', 'createdAt', 'updatedAt'] as const
  $columns = WebhookSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare storeId: string | null
  @column()
  declare name: string
  @column()
  declare url: string
  @column()
  declare secret: string
  @column()
  declare events: any | null
  @column()
  declare isActive: boolean | null
  @column.dateTime()
  declare lastTriggeredAt: DateTime | null
  @column()
  declare failureCount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WishlistItemSchema extends BaseModel {
  static $columns = ['id', 'wishlistId', 'productId', 'variantId', 'addedAt', 'notes'] as const
  $columns = WishlistItemSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare wishlistId: string | null
  @column()
  declare productId: string | null
  @column()
  declare variantId: string | null
  @column.dateTime()
  declare addedAt: DateTime
  @column()
  declare notes: string | null
}

export class WishlistSchema extends BaseModel {
  static $columns = ['id', 'customerId', 'name', 'isDefault', 'isPublic', 'shareToken', 'createdAt', 'updatedAt'] as const
  $columns = WishlistSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare customerId: string | null
  @column()
  declare name: string | null
  @column()
  declare isDefault: boolean | null
  @column()
  declare isPublic: boolean | null
  @column()
  declare shareToken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
